rails/activestorage

- lib/active_storage/service/s3_service.rb
Unless this was intentional, being consistent with:
https://github.com/rails/activestorage/blob/master/lib/active_storage/service/s3_service.rb#L8
Just showin' a lil' <3 while perusing the repo @dhh
> Fix hash usage consistency.

- lib/active_storage/service/s3_service.rb
S3 allows you to send a "content_md5" header that includes the base64 encoded md5 of the file. This checksum will then be used by S3 to verify that the file uploaded. It also has the added benefit that the checksum gets written to the object metadata for future use.
> Ensure S3 file integrity by sending checksum

- lib/active_storage/migration.rb
- test/database/create_users_migration.rb
- test/database/setup.rb
Hello,
Due to Active Support auto loading feature, the migration class shouldn't be name-spaced under the `ActiveStorage` constant, otherwise, running the migrations would throw an error.
The constant name doesn't reflect the folder structure / file name but once this got integrated into Rails, this shouldn't be a problem as it will be a template under the generator files.
Have a nice day !
> Fix the migration class name

- lib/active_storage/disk_controller.rb
- lib/active_storage/engine.rb
- lib/active_storage/service/disk_service.rb
- test/blob_test.rb
- test/disk_controller_test.rb
Since some user agents don't respect Content-Disposition filename, resulting in download filenames of `<giant SGID key>`.
> Disk storage: ensure URLs end with the blob filename

- lib/active_storage/engine.rb
- lib/active_storage/service.rb
- lib/active_storage/service/configurator.rb
- lib/active_storage/service/mirror_service.rb
- lib/active_storage/storage_services.yml
- test/service/disk_service_test.rb
- test/service/gcs_service_test.rb
- test/service/mirror_service_test.rb
- test/service/s3_service_test.rb
- test/test_helper.rb
* Move service configuration from the Engine to Service
* Delegate configuration mechanics to internal Service::Configurator
* Delegate service building to the concrete Service classes, allowing them to configure composed services.
* Implement for the Mirror service.
> Configure services that reference other services

- lib/active_storage/service.rb
- lib/active_storage/service/configurator.rb
- lib/active_storage/service/mirror_service.rb
- test/service/disk_service_test.rb
- test/test_helper.rb
* Service.build takes the literal YAML config hash for the service and a reference to the Configurator that's doing the building.
* Services that compose additional services can use the Configurator to look them up and build them by name. See MirrorService for an example.
References #23
> Clarify how a service can build other composed services

- lib/active_storage/service/configurator.rb
Since configuration is a nested hash we need to symbolize all keys
of the hash. Otherwise fetching the service configuration will fail on start
[This is the first failure point](https://github.com/rails/activestorage/blob/master/lib/active_storage/service/configurator.rb#L14)
> Symbolize all keys inside configuration nested hash

- Gemfile
- Gemfile.lock
- lib/active_storage/blob.rb
- lib/active_storage/direct_uploads_controller.rb
- lib/active_storage/engine.rb
- lib/active_storage/log_subscriber.rb
- lib/active_storage/routes.rb
- lib/active_storage/service.rb
- lib/active_storage/service/disk_service.rb
- lib/active_storage/service/s3_service.rb
- test/blob_test.rb
- test/direct_uploads_controller_test.rb
- test/disk_controller_test.rb
- test/service/s3_service_test.rb
- test/service/shared_service_tests.rb
- test/test_helper.rb
We can support direct uploads by exposing an endpoint that'll create the destination URL for the service and return a signed blob gid that can be submitted with the form on completed upload.
This pull request currently just exposes the `url_for_direct_upload` for the S3 service, but we should provide it for all services, including disk, so we can fully test it.
I'm having some trouble testing the generated URL. I can make it work with JavaScript in a browser, but stuck on something when submitting the upload request via HTTParty. Getting a signing error.
Secondly, I'd like to include the JavaScript needed to make this fully work as well. I'm thinking that we do something like `form.file_field :avatar, 'data-direct-upload': rails_direct_uploads_path` (which again should be wrapped in …
> WIP: Direct uploads

- test/service/configurator_test.rb
Test the `Configurator#build method`, just basic test which asserts resolving to the correct service instance and weather framework raises error when passing the wrong service_name value
r? @dhh
> Add basic tests to the Configurator#build

- Gemfile
- Gemfile.lock
Since we use new `aws-sdk` API(version 2), I've scoped `aws-sdk` version
so someone doesn't accidentally install wrong version during the development.
> Scope aws-skd to version 2

- lib/active_storage/service/s3_service.rb
* Use simple core API for duck-type compat with other clients
* initialize: accept an existing client
* initialize: accept arbitrary client args instead of a fixed, required set
* download: use native get_object streaming, no need to implement range requests
* exists?: use head_object (which returns immediately) rather than waiting for existence
> S3: slim down service implementation

- lib/active_storage/service/gcs_service.rb
Removing unnecessary variables inside`exist? and url` methods on `GcsService`
> Ruby assignment always returns the right-hand side; no need to use the intermediate local var.
@jeremy
> Remove unnecessary variables from gcs_service implementation

- test/service/s3_service_test.rb
So tests are passing if the bucket name is `rails-activestorage`.
But developers specify their own s3 tests configuration (in my case was
`activestorage-test`) then this regex fails.
Also the first part of url is dynamic and based on bucket name and region
`https://<bucket name>.s3.<region>.amazonaws.com...`
> Fix regular expression on s3 test URL generation test

- .codeclimate.yml
- .rubocop.yml
- Gemfile
- Gemfile.lock
- lib/active_storage/disk_controller.rb
- lib/active_storage/download.rb
- lib/active_storage/service.rb
- lib/active_storage/service/disk_service.rb
- lib/active_storage/service/s3_service.rb
- lib/active_storage/verified_key_with_expiration.rb
- lib/tasks/activestorage.rake
- test/attachments_test.rb
- test/blob_test.rb
- test/database/setup.rb
- test/filename_test.rb
- test/service/configurator_test.rb
- test/service/disk_service_test.rb
- test/service/mirror_service_test.rb
Better to write code directly respecting [rails' style guide](https://github.com/rails/rails/blob/master/.rubocop.yml) from early time so we save us some trouble when merging into rails.
Did a slight change in the `.rubocop.yml` by targeting ruby 2.3 rather than ruby 2.2 because the safe navigation operator is used.
Should we setup codeclimate for this repo?
> Added rubocop / codeclimate config and fixed current offenses

- lib/active_storage/service/gcs_service.rb
Revert `exist? and url` to the original implementation.
Since the new one doesn't provide any benefits and makes implementation
harder to follow.
Related to [43](https://github.com/rails/activestorage/pull/43)
r? @georgeclaghorn
> Revert back to the original implementaion with varaibles

- lib/active_storage/engine.rb
- lib/active_storage/storage_services.yml
Helpful error messages for two mistakes I made while setting up. Had to read the source to understand them.
1. No AWS keys in secrets.yml, but AWS is in storage_services.yml (it's there by default) -> avoid error
2. No `config.active_storage.service` for current env -> better error message
> Useful error messages for two possible misconfigurations

- lib/active_storage/log_subscriber.rb
Adding rails 5.2.0.alpha as a dependency causes sumthing like this error:
```
..Could not log "service_upload.active_storage" event. RuntimeError: can't modify frozen String
["/home/travis/build/rails/activestorage/lib/active_storage/log_subscriber.rb:6:in `service_upload'",
"/home/travis/build/rails/activestorage/vendor/bundle/ruby/2.4.0/bundler/gems/rails-c1f9fa8c6959/activesupport/lib/active_support/subscriber.rb:101:in `finish'",
"/home/travis/build/rails/activestorage/vendor/bundle/ruby/2.4.0/bundler/gems/rails-c1f9fa8c6959/activesupport/lib/active_support/log_subscriber.rb:84:in `finish'",
"/home/travis/build/rails/activestorage/vendor/bundle/ruby/2.4.0/bundler/gems/rails-c1f9fa8c6959/activesupport/lib/active_support/notifications/fanout.rb:104:in `finish'", …
```
> Fixing logger to work with Rails 5.2.0.alpha

- lib/active_storage/service/s3_service.rb
Since S3 is a published protocol, it doesn't necessarily follow that an Active Storage user will always want to use S3 storage against Amazon's cloud.
The Amazon SDK being used by Active Storage supports an additional endpoint parameter to enable support for hosted S3.
This change allows an optional `endpoint` parameter to be added to the config yaml i.e. the default behaviour is still to use Amazon's own cloud but it may be overridden if the user chooses to do so.
> Allow custom endpoints for S3.

- lib/active_storage/service/gcs_service.rb
- test/direct_uploads_controller_test.rb
- test/service/gcs_service_test.rb
Google Cloud Storage does not ask you to (or allow?) specify the content
length up front, so that parameter is ignored right now. Otherwise, the
functionality is similar to the S3 service's direct upload capability.
The integration test for uploading the written URL was failing similarly
to David's S3 test when using HTTParty. Dropping down to use Net::HTTP
allows the test to complete successfully by writing and then downloading
the resulting file.
Closes #30
> Add direct upload support to GCS service

- test/direct_uploads_controller_test.rb
- test/service/s3_service_test.rb
- test/service/shared_service_tests.rb
Hi there.
I'm replacing the bucket name section of the S3 URL with the value in the configuration hash. This allows folks to configure their own S3 information in `configurations.yml` and have a passing test  when running locally.
Thank you.
> Swap hard-coded S3 URL in DirectUploadsControllerTest with config hash value.

- lib/active_storage/service/s3_service.rb
- test/service/s3_service_test.rb
Adds the ability to supply options such server_side_encryption for S3 upload vi an upload_options parameter in storage_services.yml. upload_options are deleted from the **options parameter because server_side_encryption can not be passed into Aws::S3::Resource.new
```
upload_options:
server_side_encryption: 'AES256'
```
Due to the fact that gcs encrypts uploads by default, I did not feel it was worth making this something that could be set on a per model basis. 
Thanks!
> Add S3 upload options (server_side_encryption)

- .rubocop.yml
- Gemfile
- app/controllers/active_storage/variants_controller.rb
- config/routes.rb
- lib/active_storage/engine.rb
- lib/active_storage/variation.rb
- test/variant_test.rb
This PR fixes the following offenses and warnings.
```console
% bundle exec rubocop
/Users/koic/src/github.com/rails/activestorage/.rubocop.yml: Style/CaseIndentation has the wrong namespace - should be Layout
/Users/koic/src/github.com/rails/activestorage/.rubocop.yml: Style/CommentIndentation has the wrong namespace - should be Layout
/Users/koic/src/github.com/rails/activestorage/.rubocop.yml: Style/EmptyLines has the wrong namespace - should be Layout
/Users/koic/src/github.com/rails/activestorage/.rubocop.yml: Style/EmptyLinesAroundClassBody has the wrong namespace - should be Layout
/Users/koic/src/github.com/rails/activestorage/.rubocop.yml: Style/EmptyLinesAroundMethodBody has the wrong namespace - should be Layout
/Users/koic/src/github.com/rails/activestorage/.rubocop.yml: …
```
> Fix RuboCop offenses and warnings

- lib/active_storage.rb
This is a engine so we don't need to check weather `rails` is defined.
> This is a engine so rails must be defined

- test/controllers/variants_controller_test.rb
- test/models/variant_test.rb
- test/test_helper.rb
#72: ~~`#signature` may miss small discrepancies (e.g. image width 200 instead of 100), but gross mistakes it catches (e.g. image width 500 instead of 100 or it not being monochrome)~~
`#signature` catches even the slightest discrepancies.
> Compare images by MiniMagik.signature instead of byte-matching

- Gemfile
- Gemfile.lock
- README.md
- config/storage_services.yml
- lib/active_storage/service/azure_service.rb
- test/controllers/direct_uploads_controller_test.rb
- test/service/azure_service_test.rb
- test/service/configurations-example.yml
Add support for 3th major storage player.
This is still work in progress.  Basic upload, url generation and download are working. I have to figure out how to generate signed urls and test the whole thing.
@dhh  should we support Azure, If yes I can continue to work on the PR ?
Todo:
> Azure Storage support
